name: Build and test wheels

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ published ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        # 複数のPythonバージョンとアーキテクチャをサポート
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
        # テストコマンド
        CIBW_TEST_COMMAND: python -c "import audio_devices; devices = audio_devices.list_audio_devices(); print(f'Found {len(devices)} audio devices')"
        # Windows固有の設定
        CIBW_BEFORE_BUILD_WINDOWS: pip install setuptools wheel
        # macOS固有の設定  
        CIBW_BEFORE_BUILD_MACOS: pip install setuptools wheel

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  # ソース配布物のビルド
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v3
      with:
        name: cibw-sdist
        path: dist/*.tar.gz


